// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyApi.Models;

namespace PolicyApi.Migrations
{
    [DbContext(typeof(PolicyDetailContext))]
    [Migration("20211110103505_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PolicyApi.Models.PolicyDetail", b =>
                {
                    b.Property<int>("Policy_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Collision")
                        .HasColumnType("bit");

                    b.Property<bool>("Comprehensive")
                        .HasColumnType("bit");

                    b.Property<string>("CustomerRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Customer_Id")
                        .HasColumnType("int");

                    b.Property<string>("DateOfPurchase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fuel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncomeGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InjuryLiability")
                        .HasColumnType("bit");

                    b.Property<bool>("MaritalStatus")
                        .HasColumnType("bit");

                    b.Property<bool>("Personal")
                        .HasColumnType("bit");

                    b.Property<int>("Premium")
                        .HasColumnType("int");

                    b.Property<bool>("Property")
                        .HasColumnType("bit");

                    b.Property<string>("VehicleSegment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Policy_Id");

                    b.ToTable("PolicyDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
